# Generated by Django 3.1.3 on 2020-12-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('wage', models.FloatField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('job_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuickApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicant')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.joblisting')),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='application',
            field=models.ManyToManyField(through='jobs.QuickApply', to='accounts.Applicant'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtype'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='preferred_skill1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferredSkill1', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='preferred_skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferredSkill2', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='preferred_skill3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferredSkill3', to='jobs.skill'),
        ),
    ]
