# Generated by Django 3.1.3 on 2020-12-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skill_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skill_1', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skill_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skill_2', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skill_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skill_3', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skill_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skill_4', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skill_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skill_5', to='jobs.skill'),
        ),
    ]
